### ISSUE TITLE
WebUI Bug

### ISSUE THREAD

**Issue by anon97945** [hikariatama/Hikka#35] opened 2022-05-19 09:35 UTC
- [x] This bug **is related to Hikka userbot itself**. It **is not related to modules**.
---
**Describe the bug**
WebUI Inlinebot is buggy. When i try to add a username i get `Custom bot setting error`. When i use it without a name i get `Login confirmation error` but if I try it repeatedly, about once every 3 seconds (still getting the error), it eventually works. You can see it best when BotFather starts creating.

**To Reproduce**
1. Go to webui
2. Add new phone
3. fully login
4. at inline bot creation put in a username (or without username for other error)
5. See error

**Screenshots**
![photo_2022-05-19_10-53-16](https://user-images.githubusercontent.com/54719502/169262441-09e30ca3-2cde-42d8-ab51-c0aadacb951f.jpg)
![photo_2022-05-19_11-32-05](https://user-images.githubusercontent.com/54719502/169262445-76a28fe1-e98b-457d-9dab-d47eb9a59757.jpg)

**Userbot installation info:**
 - Platform:
- [ ] 🕶️ Termux
- [ ] ✌️ lavHost
- [ ] ☁️ Okteto
- [x] 🐳 Docker
- [ ] 🌺 Other platform

- Hikka version: 
1.1.22 #90b5ab0b (https://github.com/hikariatama/Hikka/commit/90b5ab0b4d413d4d5e299ad2135b23dbb1f8beab)

**Additional context**

**Comment by hikariatama** [comment] 2022-05-19 11:53
Was not able to reproduce issue. Please, attach errors from browser debugging console (F12)

**Comment by hikariatama** [comment] 2022-06-11 18:53
Closing, as no additional info was provided. Prob, issue was fixed in web updates

**Closed by hikariatama** 2022-06-11 18:53 UTC
Labels: bug, minor, Hikka
